### ISSUE TITLE
Income Classification

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#33] opened 2021-06-08 10:59 UTC
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/overload10/adult-census-dataset) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper [project structure](https://github.com/prathimacode-hub/ML-ProjectKart#project-structure) for code as well as for the README.
Happy coding :)

**Comment by ritikkumar55** [comment] 2021-06-11 14:19
Hey I'm a LGM-SoC participant. Can you assign me this issue. I will use multiple machine learning algorithms to draw comparisons and will use streamlit to deploy my machine learning model.

**Comment by prathimacode-hub** [comment] 2021-06-11 15:19
So, you will be working on "Model Creation"? What algorithms would you use? @ritikkumar55

**Comment by ritikkumar55** [comment] 2021-06-11 15:24
> So, you will be working on "Model Creation"? What algorithms would you use? @ritikkumar55

I will use Logistic Regression.
Naïve Bayes
Xgboost Classifier.
K-Nearest Neighbours.
Decision Tree.
Random Forest.
Support Vector Machine.

**Comment by prathimacode-hub** [comment] 2021-06-11 15:38
Ok, that sounds interesting. So you go with "Model Creation"? @ritikkumar55

**Comment by ritikkumar55** [comment] 2021-06-11 16:37
> Ok, that sounds interesting. So you go with "Model Creation"? @ritikkumar55

Yes Mam.

**Comment by prathimacode-hub** [comment] 2021-06-11 16:40
Issue is assigned to you. You can proceed.@ritikkumar55

**Comment by ritikkumar55** [comment] 2021-06-11 16:42
> Issue is assigned to you. You can proceed.@ritikkumar55
Thank you Mam.

**Comment by prathimacode-hub** [comment] 2021-06-19 09:39
It's been 8 days. As said, time to complete PR is only 5 days and no update since then. I already mentioned, you should update your progress once in 2 days. @ritikkumar55

**Closed** 2021-06-20 13:13 UTC
Labels: Assigned, LGMSOC21, Model Creation
