### ISSUE TITLE
COVID19_Data-Analysis

### ISSUE THREAD

**Issue by HitainKakkar** [prathimacode-hub/ML-ProjectKart#95] opened 2021-06-15 04:39 UTC
Greetings Sir/Mam,

I would like to work on this project and contribute!!
For this I have prepared a Jupyter notebook for the main code/analysis and 2 datasets.
Kindly assign me this issue.
This is regarding LGMSOC.

{Description of project}
This project helps us calculate and visualize the relationship between the spread of Corona virus in a country and how happy people are living in that country by merging two different datasets . The two datasets used includes First, Covid-19 dataset published by Jonh Hopkins university which cantains datasets related to cumulative number of confirmed cases countries per day and second, a dataset related to world happiness report, an annual publication by the United Nations.

**Comment by Manasi2001** [comment] 2021-06-15 17:30
Sounds really good @HitainKakkar. So, for now you'll be focusing on analysis and model creation right? If you feel like, then you can work on frontend and backend as well.

**Comment by HitainKakkar** [comment] 2021-06-15 18:51
I am interested in Backend/ Model creation.

**Comment by prathimacode-hub** [comment] 2021-06-16 09:57
Ok, this issue is assigned to you. You can proceed. But let us know about the task you'll working on so that we can assign labels accordingly? @HitainKakkar

**Comment by harshita9621** [comment] 2021-06-16 18:27
Hii, I would like to work on this issue as LGM SOC'21 participant . Do assign me if possible. Thank You!

**Comment by shivani6320** [comment] 2021-06-17 09:44
Hello. I would like to contribute to this project as aLGMSOC21 Participant. Please assign me this issue. Thank you.

**Comment by Manasi2001** [comment] 2021-06-17 09:45
@harshita9621 you can work on this, but first let me know how you are planning to proceed, what all algorithms you will use and which task you'll be working on: backend, frontend or model creation. Then, I'll assign it to you :)

And @HitainKakkar no need to worry. You can still work on this in future, I'll keep the issue open.

**Comment by Manasi2001** [comment] 2021-06-17 09:47
> Hello. I would like to contribute to this project as aLGMSOC21 Participant. Please assign me this issue. Thank you.

Hey @shivani6320, what type of analysis are you planning to do? Please elaborate in detail.

**Comment by harshita9621** [comment] 2021-06-17 10:06
I have a data set from kaggle in which they give us all the cases of covid in a day basis. So I will create a model which predict the upcoming month cases. And I use algorithms for continuous variable because our target variable will be continuous variable and algorithm Like Linear regression and random Forest regressor

**Comment by Manasi2001** [comment] 2021-06-17 10:26
Great @harshita9621, go ahead. 👍🏻

**Comment by Manasi2001** [comment] 2021-06-21 05:25
Hey peeps! This project being a being very popular choice is opened again for your contributions. But you can only do the analysis that has not been done before. So, if you feel like you can bring something new to the table then show your interest and get this issue assigned to you.

**Comment by abhisheks008** [comment] 2021-06-28 07:29
Hey @prathimacode-hub and @Manasi2001 Can you pls share the dataset which is used here?

**Comment by prathimacode-hub** [comment] 2021-06-28 08:02
Here is the dataset for COVID-19 Analysis. You can choose any one of the 2 datasets to perform COVID-19 Data Analysis.

Dataset 1 : https://www.kaggle.com/allen-institute-for-ai/CORD-19-research-challenge (or)

Dataset 2 : https://www.kaggle.com/imdevskp/corona-virus-report 

All the Best. @abhisheks008

**Comment by abhisheks008** [comment] 2021-06-28 08:03
After watching the analysis made by @harshita9621 on Covid 19 Analysis [Issue #95], I would like add more on the Exploratory Data Analysis. These are following points that I am going to add -
1. How many countries were affected by Covid-19 [Visualization]
2. Percentage of confirmed cases hold by the countries [visualization]
3. Top 5 worst affected countries [Visualization]
4. Recovered v/s Death Cases in top countries
5. China - The first epicenter [proof]
6. Cases in around the world except China
7. Conditions of the major countries -
    -  Italy
    - USA
    - South Korea
    - United Kingdom
    - Germany
    - Japan
    - Australia
    - India
8. Add on! Checking that whether the implementation of the Nationwide Lockdown in the major countries were fruitful enough or, not?

For these kind of analysis I would like to several types of the visualization methods, and then concluding the analysis with proper observation.

The dataset I am going to use is collected from Kaggle. Here is the link : https://www.kaggle.com/sudalairajkumar/novel-corona-virus-2019-dataset

**Comment by abhisheks008** [comment] 2021-06-28 08:03
> Here is the dataset for COVID-19 Analysis. You can choose any one of the 2 datasets to perform COVID-19 Data Analysis.
> 
> Dataset 1 : https://www.kaggle.com/allen-institute-for-ai/CORD-19-research-challenge (or)
> 
> Dataset 2 : https://www.kaggle.com/imdevskp/corona-virus-report
> 
> All the Best. @abhisheks008

Actually I thought of other dataset

**Comment by prathimacode-hub** [comment] 2021-06-28 08:11
Sure, you can proceed. No worries. As you had asked for dataset, i suggested. You're free to work on yours. By the way, I had created a new repo of [Covid-19 Data Analysis](https://github.com/prathimacode-hub/ML-ProjectKart/tree/main/Covid-19%20Data%20Analysis). In this repo, you can add up your Full Name as your folder title. Inside that, you can follow the project structure as usual. So that, mulitple persons can work on this issue, and their way if analysis can be differentiated by their names. @abhisheks008

**Comment by abhisheks008** [comment] 2021-06-28 08:12
Great!!

**Comment by prathimacode-hub** [comment] 2021-07-04 05:11
This issue is again open for contributions. These are the datasets to follow. You can choose either of one and provide your analysis. 

Dataset 1 : https://www.kaggle.com/allen-institute-for-ai/CORD-19-research-challenge (or)

Dataset 2 : https://www.kaggle.com/imdevskp/corona-virus-report (or)

Dataset 3 : https://www.kaggle.com/sudalairajkumar/novel-corona-virus-2019-dataset

By the way, I had created a new repo of [Covid-19 Data Analysis](https://github.com/prathimacode-hub/ML-ProjectKart/tree/main/Covid-19%20Data%20Analysis). In this repo, you can add up your Full Name as your folder title. Inside that, you can follow the project structure as usual. So that, mulitple persons can work on this issue, and their way of analysis can be differentiated by their names.

**Comment by SuryanshNaugraiya** [comment] 2021-07-04 06:53
@prathimacode-hub please assign this issue #307  to me. I want to contribute in this.

**Closed** 2021-08-04 12:38 UTC
Labels: invalid
