### ISSUE TITLE
Mobile Price Range Classification

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#34] opened 2021-06-08 11:04 UTC
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/iabhishekofficial/mobile-price-classification?select=train.csv) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper [project structure](https://github.com/prathimacode-hub/ML-ProjectKart#project-structure) for code as well as for the README.
Happy coding :)

**Comment by PaliwalRP** [comment] 2021-06-14 08:59
I would like to work on it , will you please assign me this mam.

**Comment by prathimacode-hub** [comment] 2021-06-14 09:01
What's your approach? How would you classify? What algorithms would you use. @PaliwalRP

**Comment by PaliwalRP** [comment] 2021-06-14 09:39
By datsets we can have different parmetres like as given in provided data set battery , 4g acquiring or not etc.Logistic Regression , Supervise ML algo(for classification and regression) or Decision Tree Classifier(Through R) , KNN etc.

**Comment by PaliwalRP** [comment] 2021-06-14 09:42
whichever having highest accuracy , chosen accordingly.

**Comment by prathimacode-hub** [comment] 2021-06-14 09:55
Ok that sounds good. This issue is assigned to you. @PaliwalRP

**Comment by PaliwalRP** [comment] 2021-06-14 10:10
ok will be creating PR as soon as possible.

**Comment by prathimacode-hub** [comment] 2021-06-19 09:38
It's been 5 days. As said, time to complete PR is only 5 days and no update since then. I already mentioned, you should update your progress once in 2 days. @PaliwalRP

**Comment by PaliwalRP** [comment] 2021-06-19 10:42
Really sorry about that mam , but my system went into some problem so i was not able to carry out the work further.It will take around more 5 days for my system to get repair.You can assign this issue to someone if he/she wants to work on it i will also sumbit a PR if my system repaires within the time frame.

**Comment by prathimacode-hub** [comment] 2021-06-19 13:21
Ok, sure. @PaliwalRP

**Comment by PaliwalRP** [comment] 2021-06-19 13:55
I wanted to contribute but , its not possible without system.I will try if i get it reapired in a 2-3 days.

**Comment by prathimacode-hub** [comment] 2021-06-19 15:32
Sorry, I had removed the tag. Do you want me to add up still? @PaliwalRP

**Comment by PaliwalRP** [comment] 2021-06-19 16:28
No mam its okay , I was just saying that in case i get my system back in 2-3 days i will reach out to this issue again.

**Comment by Isha307** [comment] 2021-06-20 05:19
@prathimacode-hub Can I work on this issue ?

**Comment by prathimacode-hub** [comment] 2021-06-20 14:34
Are you sure, you want to work on this? Kindly let me know of the approach you will follow, algorithms you would take up and the task you're going to choose? @Isha307

**Comment by Isha307** [comment] 2021-06-20 16:52
I will create model for the price prediction on the basis of given features.
I will check accuracy of different algorithm(mainly classification) and will chose accordingly.

**Comment by prathimacode-hub** [comment] 2021-06-20 16:57
That's cool. Issue is assigned. You can start working. @Isha307

**Closed** 2021-06-21 15:20 UTC
Labels: Assigned, LGMSOC21, Model Creation
