### ISSUE TITLE
IPL Score Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#36] opened 2021-06-08 16:07 UTC
Hey LGM-SoC participants, good to see you.

This project predicts the score across the IPL 2020 season.

Dataset : https://www.kaggle.com/laxmena/ipl-dataset-2020-season-included

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

Enjoy your open source journey!😎

**Comment by harshita9621** [comment] 2021-06-09 09:44
Hii, I would like to work on this issue as LGM SOC'21 participant from June 10. Do assign me if possible. Thank You!

**Comment by sy07** [comment] 2021-06-09 18:09
Hi mam, I would like to work on this issue as LGM-SOC'21 participant from June 10. Do assign me if possible.
Thank You!

**Comment by prathimacode-hub** [comment] 2021-06-09 18:15
Good to see your interest with the issue. But assignment to issues for ML-ProjectKart would start from June10th, 10AM. It would be on FCFS basis. So be prompt enough to respond after the given time. Only participants who expresses their interest first after 10AM would be assigned with the issue. Also I had added up an enclosed document of things you need to follow. It's pinned to the project channel in slack. Do check it out and keep it as a reference. @harshita9621 @sy07

**Comment by sy07** [comment] 2021-06-09 18:21
Mam can you please share the link of project channel. which is on slack

**Comment by sy07** [comment] 2021-06-10 04:30
Hi mam, I would like to work on this issue as LGM-SOC'21 participant from June 10. Do assign me this task if possible. I would like to work on data.
Thank You!

**Comment by prathimacode-hub** [comment] 2021-06-10 04:50
I shall assign this task to you but let me know of task you want to work on : Model creation or front end or back end or designing @sy07

**Comment by sy07** [comment] 2021-06-10 04:52
> I shall assign this task to you but let me know of task you want to work on : Model creation or front end or back end or designing @sy07

mam i want to work on model creation.

**Comment by sy07** [comment] 2021-06-10 05:02
Mam i would like to work on this issue first.

**Comment by prathimacode-hub** [comment] 2021-06-10 05:04
Ok, Assigned this task to you. @sy07

**Comment by sy07** [comment] 2021-06-10 05:04
Thank you mam.

**Comment by Sumit11081996** [comment] 2021-06-16 18:34
hii @prathimacode-hub  can you please assign me this

**Comment by jayant766** [comment] 2021-06-17 09:13
please assign it to me under LGM-SOC'21

**Comment by Manasi2001** [comment] 2021-06-17 09:36
@Sumit11081996 you can work on this. Please let me know what all algorithms you will use and which task you'll be working on: backend, frontend or model creation. Then, I'll assign it to you.

**Comment by shivani6320** [comment] 2021-06-17 09:48
Hello. I would like to contribute to this project as aLGMSOC21 Participant. Please assign me this issue. Thank you.

**Comment by Manasi2001** [comment] 2021-06-17 09:50
@jayant766 and @shivani6320 the issues are assigned on the basis of FCFS and you can only work on one issue at a time. Please select one and let me know.

**Comment by jayant766** [comment] 2021-06-17 09:57
@Manasi2001 According to the rule the issue will assign to me because I first come.

**Comment by Manasi2001** [comment] 2021-06-17 10:03
Hey @jayant766, Sumit asked for the issue to be assigned to him before you.
![image](https://user-images.githubusercontent.com/68627617/122375615-04037b80-cf81-11eb-84f0-189ede8ee37e.png)
Don't you worry, there are so many projects that you can work on, just select 1 and I'll assign it to you. 🙃

**Comment by jayant766** [comment] 2021-06-17 10:05
@Manasi2001 I didn't saw his comment, if he came first then assigned it to him. I don't have any problem.

**Comment by Sumit11081996** [comment] 2021-06-18 03:57
There is a delivery data set in kaggle in which they give us all the runs scored in a every single ball so i can perform a EDA and extract information from the data and create a model which predict how many run scored in the next over and the target variable is continuous so i am performing algorithm which used in continuous variable Like Linear regression and random Forest regressor and decision tree regressor type.

**Comment by prathimacode-hub** [comment] 2021-06-18 07:09
Cool, what's the task you will be working on? @Sumit11081996

**Comment by Sumit11081996** [comment] 2021-06-18 07:11
@prathimacode-hub  model creation

**Comment by prathimacode-hub** [comment] 2021-06-18 07:21
Issue is assigned to you. @Sumit11081996

**Comment by prathimacode-hub** [comment] 2021-06-25 11:42
No update from you. @Sumit11081996

**Comment by prathimacode-hub** [comment] 2021-06-28 06:11
It's been long time. Need update from you. @Sumit11081996

**Comment by Soumayan-pal01** [comment] 2021-06-28 09:44
Can I work on 'Model Creation' for this issue @prathimacode-hub .

**Comment by prathimacode-hub** [comment] 2021-06-28 09:45
Sumit is assigned with this issue for "Model Creation". Let's wait for more 3 days. If he doesn't respond, I will keep this issue open.

**Comment by Soumayan-pal01** [comment] 2021-06-28 09:50
Okhay @prathimacode-hub

**Comment by prathimacode-hub** [comment] 2021-06-28 10:00
@Sumit11081996, If you don't respond within 2 days, I'm sorry to say, but I have to assign it to someone else. You can't hold an issue for very long. It's been 10days without any update.

**Comment by SuryanshNaugraiya** [comment] 2021-07-02 10:44
> Hey LGM-SoC participants, good to see you.
> 
> This project predicts the score across the IPL 2020 season.
> 
> Dataset : https://www.kaggle.com/laxmena/ipl-dataset-2020-season-included
> 
> If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.
> 
> Enjoy your open source journey!😎

hi @prathimacode-hub according to your task, i have followed every step and i have created an amazing end to end project that predicts the ipl score and winner as well. below i have attached the screenshots of my project. please assign this issue to me. #36
![Screenshot (254)](https://user-images.githubusercontent.com/53707393/124262831-2801b800-db50-11eb-9489-efd20ac6a31b.png)
![Screenshot (255)](https://user-images.githubusercontent.com/53707393/124262847-2d5f0280-db50-11eb-9488-c462950196e5.png)
![Screenshot (256)](https://user-images.githubusercontent.com/53707393/124262860-30f28980-db50-11eb-81a7-c495980267be.png)
![Screenshot (257)](https://user-images.githubusercontent.com/53707393/124262869-33ed7a00-db50-11eb-88db-2955d9c8ba8b.png)
![Screenshot (258)](https://user-images.githubusercontent.com/53707393/124262877-37810100-db50-11eb-9137-973e66e57082.png)
![Screenshot (259)](https://user-images.githubusercontent.com/53707393/124262891-3a7bf180-db50-11eb-890f-1342c1e096f7.png)
![Screenshot (263)](https://user-images.githubusercontent.com/53707393/124262897-3d76e200-db50-11eb-861d-312ecbe8d028.png)
![Screenshot (264)](https://user-images.githubusercontent.com/53707393/124262906-3f40a580-db50-11eb-8bd3-6b096724dde7.png)
![Screenshot (265)](https://user-images.githubusercontent.com/53707393/124262911-410a6900-db50-11eb-8005-555534c074ed.png)
![Screenshot (266)](https://user-images.githubusercontent.com/53707393/124262920-423b9600-db50-11eb-8c4c-bde0b6839189.png)
![Screenshot (267)](https://user-images.githubusercontent.com/53707393/124262928-44055980-db50-11eb-8262-a0034cdd5545.png)
![Screenshot (268)](https://user-images.githubusercontent.com/53707393/124262933-45cf1d00-db50-11eb-8bfa-8dabd1bf3b98.png)

**Comment by prathimacode-hub** [comment] 2021-07-02 10:55
Wow, that's amazing. One of the participant had taken up an issue of IPL Winner Prediction, but you had done both the things. So lets plan this way, the participant who had taken 'IPL Winner Prediction' will be doing model creation. You can do full end to end for 'IPL Score Prediction' for now. And after the participant submits up his PR, you can enhance that project more briefer with Front End and Back End. So that would be total of 2 PR's you would be doing. If this is ok with you? @SuryanshNaugraiya

**Comment by SuryanshNaugraiya** [comment] 2021-07-02 11:08
no problem, so now it means that i have to upload my complete project 2 times , 1st time here and 2nd time at different issue, right?

**Comment by prathimacode-hub** [comment] 2021-07-02 11:29
Yes, right. Even the PR you submit for this issue should be according to requirements this issue suffices. This would be complete project. Later other PR, would be an enhancement to project submitted by other participant obviously through different issue.

**Comment by SuryanshNaugraiya** [comment] 2021-07-02 12:12
hey @prathimacode-hub i have created a pull request #300 please check it and merge it

**Closed** 2021-07-07 08:09 UTC
Labels: Assigned, LGMSOC21, Model Creation
