### ISSUE TITLE
Car Prices Prediction

### ISSUE THREAD

**Issue by vijay3150** [prathimacode-hub/ML-ProjectKart#493] opened 2021-07-26 04:55 UTC
Define You:

- [ ] LGM-SOC'21 Participant 
- [/ ] DevIncept Participant
- [/ ] Contributor

Tiltle : used car prediction .
aim : to predict the price of various used car 
dataset : https://www.kaggle.com/avikasliwal/used-cars-price-prediction

assign me to do the project.

**Comment by prathimacode-hub** [comment] 2021-07-26 14:23
Are you a participant of LGMSOC or Devincept? @vijay3150

**Comment by vijay3150** [comment] 2021-07-26 14:30
Devincept mam

**Comment by prathimacode-hub** [comment] 2021-07-27 08:04
Ok issue assigned. @vijay3150

**Comment by prathimacode-hub** [comment] 2021-08-02 12:56
Its been 6 days and no update from you yet. @vijay3150

**Comment by vijay3150** [comment] 2021-08-03 03:11
Done its ready to complete, sure i submit today mam.

**Comment by vijay3150** [comment] 2021-08-04 03:21
mam, my laptop has some issue and the data were removed and I think I am unable to contribute towards the project so un assign me from this project mam

**Comment by akash435** [comment] 2021-08-06 15:59
@prathimacode-hub Can I work on this issue?

I will use different visualization graph and

will use different algorithms like
decision tree regression
Random Forest classifier
K Neighbor Classifier
XG boost classifier

and compare the the accuracy among them

**Comment by prathimacode-hub** [comment] 2021-08-06 16:02
Yes, you can. Issue assigned.

**Comment by prathimacode-hub** [comment] 2021-08-09 08:24
Ooops, I am sorry to say but this issue is already done. Since issue is already assigned Its not right to get you back off. So let's do one thing. In "Car Prices Prediction" folder, add up your full name as your project folder and in that particular repo do add all your files in right project structure as you had done earlier. @akash435

**Comment by prathimacode-hub** [comment] 2021-08-09 16:57
Kindly do it by tomorrow. As last date to merge PR is tomorrow. @akash435

**Comment by akash435** [comment] 2021-08-09 17:00
yes mam, tomorrow I will.

**Closed** 2021-08-10 07:34 UTC
Labels: Assigned, Model Creation, LGMSOC21
