### ISSUE TITLE
U.S. weather history visualization

### ISSUE THREAD

**Issue by HitainKakkar** [prathimacode-hub/ML-ProjectKart#172] opened 2021-06-21 15:41 UTC
#180 
Greetings Sir/Mam,

I would like to work on this project and contribute!!
For this I have prepared a Jupyter notebook for the main code/analysis and 2 datasets.
Kindly assign me this issue.
This is regarding LGMSOC.
I have made the Pull Request for the same #180 

{Description of project}

### U.S. weather history visualization

The raw data and code behind the story [What 12 Months Of Record-Setting Temperatures Looks Like Across The U.S.](http://fivethirtyeight.com/features/what-12-months-of-record-setting-temperatures-looks-like-across-the-u-s/)

Source: [Weather Underground](http://wunderground.com)

**Comment by Manasi2001** [comment] 2021-06-21 18:00
DO NOT MAKE THE PR UNTIL THE ISSUE IS ASSIGNED TO YOU.
This should be the first and the last time, okay?

**Closed** 2021-06-22 12:40 UTC
Labels: Assigned, LGMSOC21
